---
name: kics
on:
  pull_request:
    branches: ["master"]

jobs:
  kics:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        name: Check out source code

      - name: run a KICS scan
        uses: checkmarx/kics-github-action@6b6fc1162a0f06704e4cca6e5f8e008ab20fabe5
        with:
          path: .
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: myResults/
